kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ignite-role-binding
roleRef:
  kind: Role
  name: ignite-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ignite-sa
    namespace: yyc-test