apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ignite-role
  namespace: yyc-test # Specify the namespace
rules:
  - apiGroups:
      - ""
    resources: # Here are the resources you can access
      - pods
      - endpoints
    verbs: # That is what you can do with them
      - get
      - list
      - watch