apiVersion: apps/v1
kind: Deployment
metadata:
  name: deptrack-api
  namespace: deptrack
spec:
  replicas: 1
  selector:
    matchLabels:
      ManagedBy: deptrack-operator
      component: api-server
  template:
    metadata:
      labels:
        ManagedBy: deptrack-operator
        component: api-server
    spec:
      containers:
        - command:
            - /agnhost
            - netexec
            - --http-port=8080
          image: registry.k8s.io/e2e-test-images/agnhost:2.39
          imagePullPolicy: IfNotPresent
          name: agnhost
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
      restartPolicy: Always

