apiVersion: apps/v1
kind: Deployment
metadata:
  name: yyc-{{ .Chart.Name }}
  namespace: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: yyc-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        name: yyc-{{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "ignite-operator.serviceAccount.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "ignite-operator.imagePath" . }}
