apiVersion: v1
kind: Service
metadata:
  name: {{ include "ignite-operator.name" . }}-svc
  namespace: {{ include "ignite-operator.namespace" . }}
  labels:
    name: {{ include "ignite-operator.name" . }}
spec:
  selector:
    name: {{ include "ignite-operator.name" . }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
