apiVersion: v1
kind: Service
metadata:
  labels:
    app: ignite
  name: ignite-service
  namespace: imdb
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: thinclients
      port: 10800
      protocol: TCP
      targetPort: 10800
    - name: clusteractivate
      port: 11211
      protocol: TCP
      targetPort: 11211
  selector:
    app: ignite