apiVersion: v1
kind: Namespace
metadata:
  name: imdb
  labels:
    name: imdb

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: imdb-ignite-sa
  namespace: imdb
#  annotations:
#    iam.gke.io/gcp-service-account:

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imdb-ignite-clusterrole
  namespace: imdb
rules:
  - apiGroups:
      - ""
    resources: # Here are the resources you can access
      - pods
      - endpoints
    verbs: # That is what you can do with them
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imdb-ignite-clusterrole-binding
roleRef:
  kind: ClusterRole
  name: imdb-ignite-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: imdb-ignite-sa
    namespace: imdb